/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const DashboardStats = IDL.Record({
  'vulnerabilitiesFound' : IDL.Nat,
  'bugsFixed' : IDL.Nat,
  'totalProjects' : IDL.Nat,
  'securityScore' : IDL.Nat,
});
export const ProjectStatus = IDL.Variant({
  'Fixed' : IDL.Null,
  'InProgress' : IDL.Null,
});
export const Severity = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
  'Critical' : IDL.Null,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'status' : ProjectStatus,
  'vulnerabilityType' : IDL.Text,
  'description' : IDL.Text,
  'beforeCode' : IDL.Text,
  'targetName' : IDL.Text,
  'category' : IDL.Text,
  'severity' : Severity,
  'afterCode' : IDL.Text,
});
export const ContactInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const Result = IDL.Variant({
  'ok' : ContactSubmission,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'getContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'submitContact' : IDL.Func([ContactInput], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const DashboardStats = IDL.Record({
    'vulnerabilitiesFound' : IDL.Nat,
    'bugsFixed' : IDL.Nat,
    'totalProjects' : IDL.Nat,
    'securityScore' : IDL.Nat,
  });
  const ProjectStatus = IDL.Variant({
    'Fixed' : IDL.Null,
    'InProgress' : IDL.Null,
  });
  const Severity = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
    'Critical' : IDL.Null,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'status' : ProjectStatus,
    'vulnerabilityType' : IDL.Text,
    'description' : IDL.Text,
    'beforeCode' : IDL.Text,
    'targetName' : IDL.Text,
    'category' : IDL.Text,
    'severity' : Severity,
    'afterCode' : IDL.Text,
  });
  const ContactInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : ContactSubmission, 'err' : IDL.Text });
  
  return IDL.Service({
    'getContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'submitContact' : IDL.Func([ContactInput], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };