/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactInput {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface ContactSubmission {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface DashboardStats {
  'vulnerabilitiesFound' : bigint,
  'bugsFixed' : bigint,
  'totalProjects' : bigint,
  'securityScore' : bigint,
}
export interface Project {
  'id' : bigint,
  'status' : ProjectStatus,
  'vulnerabilityType' : string,
  'description' : string,
  'beforeCode' : string,
  'targetName' : string,
  'category' : string,
  'severity' : Severity,
  'afterCode' : string,
}
export type ProjectStatus = { 'Fixed' : null } |
  { 'InProgress' : null };
export type Result = { 'ok' : ContactSubmission } |
  { 'err' : string };
export type Severity = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null } |
  { 'Critical' : null };
export interface _SERVICE {
  'getContacts' : ActorMethod<[], Array<ContactSubmission>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getProject' : ActorMethod<[bigint], [] | [Project]>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'submitContact' : ActorMethod<[ContactInput], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];